config/routes.rb
SampleApp::Application.routes.draw do

  resources :posts

  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/instagram', to: "home#index", via: 'get'
  match '/results', to: "home#instagram_results", via: 'post'
  match '/posts', to: "posts#new", via: 'get'
  

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
require 'open-uri'
class HomeController < ApplicationController

    def index
        @instagram = Instagram.user_recent_media("459355170", {:count => 1})
        @posts = Post.where("image_url is NOT NULL and id > ?", params[:after_id])
    end

    def instagram_results
    	@brand = params[:brandname]
        tags = Instagram.tag_recent_media(@brand)
        puts tags.class

  		Resque.enqueue(ImageProcessor,tags)
  	end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    PrintWorker.perform_async(params[:to_print])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end

  def show
      @post = Post.find(params[:id])
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/home/index.html.erb
    <%# @instagram.each do |instagram| %>

    <%#= image_tag instagram.images.standard_resolution.url %>


    <%# end %>
<%# <p>   Select Brand </p> %>
<%#= select_tag(:brand_id,options_for_select([['Coca Cola', 1], ['Starbucks', 2], ['Others',3]], 1)) %>

<%#

<form accept-charset="UTF-8" action="/clients" method="post">
  <input type="text" name="client[name]" value="Acme" />
  <input type="text" name="client[phone]" value="12345" />
  <input type="text" name="client[address][postcode]" value="12345" />
  <input type="text" name="client[address][city]" value="Carrot City" />
  <input type="submit" value="Submit">
</form>

%>

<div class="row">
  <div class="span6 offset3">
	<%= form_tag("/results", method: "post") do %>
  	<%= label_tag(:brandname, "Enter brand name:") %>
  	<%= text_field_tag(:brandname) %>
 	 <%= submit_tag("Submit") %>
	<% end %>
	</div>
</div>

<% @posts.each do |p| %>

  <div class = "image" post-id ="<%= p.id %>" >

       <%= image_tag(p.image_url, size:"100x100") %>

   </div>

<% end %>

app/views/home/index.js.erb
$(".image").append("<%=raw escape_javascript(render(@posts)) %>");

app/views/home/instagram_results.html.erb
<p> <%= @brand %> </p>

<%# html = "<p> Hi </p>" %>
<%# @tags.each do |media_item| %>

    <%# link = media_item.link %>

    <%# image = media_item.images.standard_resolution.url %>

    <%# html << "<img src=#{image} />"  %>

<%# end %>

<%#= html %>
<p> <%#= @tags %> Success! </p>



<%# @tags.each do |tags| %>
    <%#= image_tag tags.images.standard_resolution.url %>
<%# end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "spotr", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right navbar-nav">
          <li><%= link_to "Home",    root_path %></li> <li><%= link_to "Help", help_path %></li> <li><%= link_to "Instagram", 'instagram' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<% @posts.each do |p| %>

	<div class = "image" post-id ="<%= p.id %>">

  		 <%= image_tag(p.image_url, size:"100x100")%>

   </div>

<% end %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<%= @post.source %>, <%= @post.image_url %>, <%= @post.processed %>, <%= @post.username %>, <%= @post.local_add %>, <%= @post.brand %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<%# provide(:title, 'Home') %>
<div class="center hero-unit">
  <h1>Welcome to Sample App home page</h1>

  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("spotr.png", alt: "spotr"), 'http://rubyonrails.org/' %>